name = "catalog-events-worker"
main = "src/index.ts"
compatibility_date = "2025-10-14"
compatibility_flags = ["nodejs_compat"]
tsconfig = "./tsconfig.json"

[[queues.consumers]]
queue = "catalog-events"
max_batch_size = 10
max_batch_timeout = 5

[[queues.producers]]
binding = "CATALOG_EVENTS_DLQ"
queue = "catalog-events-dlq"
