name = "tenant-provisioning-worker"
main = "src/index.ts"
compatibility_date = "2025-10-14"
compatibility_flags = ["nodejs_compat"]
tsconfig = "./tsconfig.json"

[[queues.consumers]]
queue = "tenant-provisioning"
max_batch_size = 5
max_batch_timeout = 5

[[queues.producers]]
binding = "TENANT_PROVISIONING_DLQ"
queue = "tenant-provisioning-dlq"
